package yugodifanananta;
public class YugoDifanAnanta {
    public static void main(String[] args) {
        System.out.println("Hai,\nSelamat datang di Java!"); // \n untuk baris baru
        
        System.out.println("Nama:\tYugo"); // \t untuk tab
        
        System.out.println("Ini adalah tanda backslash: \\"); // \\ untuk backslash
        
        System.out.println("Dia berkata: \"Java itu mudah!\""); // \" untuk tanda kutip ganda
        
        System.out.println("Karakter apostrof: \'"); // \' untuk tanda kutip tunggal
    }
    
}
