package yugodifan;
public class YugoDifan {
    public static void main(String[] args) {
        // Contoh tipe data char
        char huruf = 'A';
        char angka = '7';
        char simbol = '@';
        
        // Contoh tipe data boolean
        boolean isJavaFun = true;
        boolean isRaining = false;
        
        System.out.println("Karakter huruf: " + huruf);
        System.out.println("Karakter angka: " + angka);
        System.out.println("Karakter simbol: " + simbol);
        
        System.out.println("Apakah Java menyenangkan? " + isJavaFun);
        System.out.println("Apakah sedang hujan? " + isRaining);
    }
}
