package yugodifan;
public class YugoDifan {
    public static void main(String[] args) {
        byte a = 100;
        short b = 20000;
        int c = 1000000;
        long d = 10000000000L; // Harus ada 'L' di akhir
        
        System.out.println("Nilai byte: " + a);
        System.out.println("Nilai short: " + b);
        System.out.println("Nilai int: " + c);
        System.out.println("Nilai long: " + d);
    }
}
