package yugodifan;
public class YugoDifan {
    public static void main(String[] args) {
        // Nilai tetap untuk dua angka
        int num1 = 10;  // Bisa int atau double
        int num2 = 5;
        // Operasi penjumlahan
        int jumlah = num1 + num2;
        System.out.println("Penjumlahan (" + num1 + " + " + num2 + ")= " + jumlah);  // Output: 15
        // Operasi pengurangan
        int selisih = num1 - num2;
        System.out.println("Pengurangan (" + num1 + " - " + num2 + ")= " + selisih);  // Output: 5
    }
}
